name: Anchor Tests

on:
    push:
        branches: [main]
        paths:
            - "registry-contracts-solana/**"
            - ".github/workflows/anchor-test.yml"
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install Rust
              run: |
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
                  echo "$HOME/.cargo/bin" >> $GITHUB_PATH

            - name: Install Solana CLI
              run: |
                  sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
                  echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install AVM and Anchor CLI
              run: |
                  cargo install --git https://github.com/coral-xyz/anchor avm --force
                  avm install 0.31.0
                  avm use 0.31.0
                  echo "$HOME/.avm/bin" >> $GITHUB_PATH

            - name: Install project dependencies
              working-directory: registry-contracts-solana
              run: yarn install

            - name: Run Anchor tests
              working-directory: registry-contracts-solana
              run: anchor test
